In [ ]:
import numpy as np
from numpy.linalg import det


def metodocrammer(A, b):
    """
    Resuelve un sistema de ecuaciones lineales Ax = b utilizando la regla de Cramer.

    Parámetros:
    A (numpy.ndarray): Matriz de coeficientes del sistema.
    b (numpy.ndarray): Vector de términos independientes.

    Retorna:
    numpy.ndarray | None: Solución del sistema si tiene una única solución, de lo contrario, None.
    """
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = A.shape[1]

    dA = det(A)  # Calculamos el determinante de A
    if dA == 0:
        print("El sistema no tiene solución única.")
        return None

    soluciones = np.zeros(n)
    for i in range(n):
        Ai = A.copy()
        Ai[:, i] = b  # Reemplazamos la columna i con el vector b
        soluciones[i] = det(Ai) / dA  # Calculamos la solución usando determinantes

    return soluciones

# Definimos el tamaño de la matriz
n = 3

#  matriz A y un vector b con números enteros aleatorios entre 1 y 10
A = np.random.randint(1, 11, size=(n, n))
b = np.random.randint(1, 11, size=n)

# Imprimimos la matriz y el vector generados
print("Matriz A:")
print(A)

print("\nVector b:")
print(b)

# Resolución del sistema de ecuaciones
solucionaAyBaleatorio = metodocrammer(A, b)

# condicionamos si hay solucion o no para que se muestre su respectivo resultado
if solucionaAyBaleatorio is not None:
  print("\nSolución del sistema:")
  print(solucionaAyBaleatorio)


Matriz A:
[[ 2  3  2]
 [10 10  2]
 [ 1  4  8]]

Vector b:
[10  4 10]

Solución del sistema:
[-17.2  18.8  -6. ]


Codigo hecho en clase

In [ ]:
import numpy as np
from numpy import linalg as LA


#Crea una submatriz eliminando un renglón y una columna específicos de la matriz original.
def SubMat(Mat, ren, col):
 # Crear una copia de la matriz original para no modificarla
    M1 = np.copy(Mat)

    # Eliminar el renglón especificado
    M1 = np.delete(M1, ren, axis=0)

    # Eliminar la columna especificada
    M1 = np.delete(M1, col, axis=1)

    return M1

#Calcula el determinante de una matriz cuadrada de manera recursiva.

def Det(Mat):
   # Caso base: matriz 2x2
    if Mat.shape[0] == 2 and Mat.shape[1] == 2:
        return Mat[0][0] * Mat[1][1] - (Mat[0][1] * Mat[1][0])

    # Caso recursivo: matrices más grandes
    deter = 0.0
    for col in range(Mat.shape[0]):
        # Calcula el cofactor y suma al determinante
        deter += ((-1) ** col) * Mat[0][col] * Det(SubMat(Mat, 0, col))
    return deter

# Calcula la transpuesta de una matriz cuadrada modificando la matriz original.
def Transpuesta(Mat):
    for ren in range(Mat.shape[0]):
        for col in range(Mat.shape[1]):
            if ren < col:
                # Intercambia los elementos para obtener la transpuesta
                Mat[ren, col], Mat[col, ren] = Mat[col, ren], Mat[ren, col]
    return Mat

"Calcula la matriz de cofactores de una matriz cuadrada"
def Cofactores(Mat):
# Crear una matriz de ceros del mismo tamaño que Mat para almacenar los cofactores
    Cofa = np.zeros_like(Mat, dtype=float)

    # Calcular el cofactor para cada elemento de la matriz
    for ren in range(Mat.shape[0]):
        for col in range(Mat.shape[1]):
            # Calcular el determinante de la submatriz (menor) y aplicar el signo
            Cofa[ren, col] = ((-1) ** (ren + col)) * Det(SubMat(Mat, ren, col))
    return Cofa

"Calcula la inversa de una matriz cuadrada utilizando la matriz de cofactores"
def Inv(Mat):
  # Calcular el determinante de la matriz
    deter = Det(Mat)

    # Verificar si la matriz es singular (determinante = 0)
    if deter == 0:
        raise ValueError("La matriz es singular y no tiene inversa.")

    # Calcular la matriz de cofactores
    Cofac = Cofactores(Mat)

    # Transponer la matriz de cofactores para obtener la matriz adjunta
    Cofac = Transpuesta(Cofac)

    # Calcular la inversa multiplicando la adjunta por 1/determinante
    Inversa = (1 / deter) * Cofac

    return Inversa

"Resuelve un sistema de ecuaciones lineales utilizando la matriz inversa."
A=np.array([[9,1,10],[6,4,10],[6,5,4]])
b=np.array([1,8,3])

def SolveInv(Mat, vec):
   # Calcular la inversa de la matriz
    InvMat = Inv(Mat)

    # Multiplicar la inversa por el vector de términos independientes
    Solucion = InvMat @ vec

    return Solucion


Sol=SolveInv(A,b)
print(Sol)
Sol_python=LA.solve(A,b)
print(Sol_python)

[-1.16190476  1.17142857  1.02857143]
[-1.16190476  1.17142857  1.02857143]


In [ ]:
import numpy as np
from numpy.linalg import det


def metodocrammer(A, b):
    """
    Resuelve un sistema de ecuaciones lineales Ax = b utilizando la regla de Cramer.

    Parámetros:
    A (numpy.ndarray): Matriz de coeficientes del sistema.
    b (numpy.ndarray): Vector de términos independientes.

    Retorna:
    numpy.ndarray | None: Solución del sistema si tiene una única solución, de lo contrario, None.
    """
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    n = A.shape[1]

    dA = det(A)  # Calculamos el determinante de A
    if dA == 0:
        print("El sistema no tiene solución única.")
        return None

    soluciones = np.zeros(n)
    for i in range(n):
        Ai = A.copy()
        Ai[:, i] = b  # Reemplazamos la columna i con el vector b
        soluciones[i] = det(Ai) / dA  # Calculamos la solución usando determinantes

    return soluciones

#  matriz A y un vector b fijos
A=np.array([[9,1,10],[6,4,10],[6,5,4]])
b=np.array([1,8,3])
# Imprimimos la matriz y el vector generados
print("Matriz A:")
print(A)

print("\nVector b:")
print(b)

# Resolución del sistema de ecuaciones
solucioncrammerfijo = metodocrammer(A, b)

# condicionamos si hay solucion o no para que se muestre su respectivo resultado
if solucioncrammerfijo is not None:
  print("\nSolución del sistema:")
  print(solucioncrammerfijo)


Matriz A:
[[ 9  1 10]
 [ 6  4 10]
 [ 6  5  4]]

Vector b:
[1 8 3]

Solución del sistema:
[-1.16190476  1.17142857  1.02857143]


In [ ]:
print("Comparación de resultados ")

print("\nSolución del sistema matrix y vector fijo:")
print(solucioncrammerfijo)


print("\nSolución del sistema codigo hecho en clase :")
Sol=SolveInv(A,b)
print(Sol)

print("\nSolución del sistema A y B aleatorios:")
solucionaAyBaleatorio = metodocrammer(A, b)
print(solucionaAyBaleatorio)

Comparación de resultados 

Solución del sistema matrix y vector fijo:
[-1.16190476  1.17142857  1.02857143]

Solución del sistema codigo hecho en clase :
[-1.16190476  1.17142857  1.02857143]

Solución del sistema A y B aleatorios:
[-1.16190476  1.17142857  1.02857143]
