## **1.1Programe la multiplicación de matrices por bloques y compare tiempos de ejecuci ón contra el programa realizado en clase. Ojo, el nuevo programa debe ser más rápido, escoja tama ños de 10 hasta 100.**

In [22]:
import numpy as np
import time as time

In [3]:
def multmat(mat1, mat2):
    """
    Realiza la multiplicación de dos matrices.

    Parámetros:
    -----------
    mat1 : numpy.ndarray
        Una matriz de tamaño (n, m), donde n es el número de filas y m es el número de columnas.
    mat2 : numpy.ndarray
        Una matriz de tamaño (m, p), donde m es el número de filas y p es el número de columnas.

    Retorno:
    --------
    mat3 : numpy.ndarray
        Una matriz de tamaño (n, p) que contiene el resultado de la multiplicación.

    Ejemplo:
    --------
    >>> mat1 = np.array([[1, 2], [3, 4]])
    >>> mat2 = np.array([[5, 6], [7, 8]])
    >>> multmat(mat1, mat2)
    array([[19., 22.],
           [43., 50.]])
    """
    mat3 = np.zeros((mat1.shape[0], mat2.shape[1]))  # Inicializa la matriz de resultado con ceros

    # Itera sobre las filas de la primera matriz
    for ren in range(mat1.shape[0]):
        # Itera sobre las columnas de la segunda matriz
        for col in range(mat2.shape[1]):
            # Itera sobre los elementos comunes (columnas de mat1 y filas de mat2)
            for aux in range(mat2.shape[0]):
                mat3[ren, col] += mat1[ren, aux] * mat2[aux, col]  # Multiplica y acumula el resultado

    return mat3  # Retorna la matriz resultante

In [4]:
n=100

#declaramos los arreglos a utiliazr
a=n*[n*[2]]
b=n*[n*[4]]

#pasamos a arreglos de numpy
A=np.array(a)
B=np.array(b)

In [5]:
"""
Sola mente para visualizar como son A y B
"""
print(A,'\n',B)

[[2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 ...
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]] 
 [[4 4 4 ... 4 4 4]
 [4 4 4 ... 4 4 4]
 [4 4 4 ... 4 4 4]
 ...
 [4 4 4 ... 4 4 4]
 [4 4 4 ... 4 4 4]
 [4 4 4 ... 4 4 4]]


In [6]:
"""
Con ayuda de la biblioteca time se miden los tiempos de la función de nunpy para
multiplicar matrices, así como el algoritmo que hicimos en clase
"""

inicio = time.time()
A@B
fin = time.time()
print(fin - inicio)

print(A@B)

print(multmat(A,B))

inicio = time.time()
multmat(A,B)
fin =time.time()
print(fin-inicio)


0.002429485321044922
[[800 800 800 ... 800 800 800]
 [800 800 800 ... 800 800 800]
 [800 800 800 ... 800 800 800]
 ...
 [800 800 800 ... 800 800 800]
 [800 800 800 ... 800 800 800]
 [800 800 800 ... 800 800 800]]
[[800. 800. 800. ... 800. 800. 800.]
 [800. 800. 800. ... 800. 800. 800.]
 [800. 800. 800. ... 800. 800. 800.]
 ...
 [800. 800. 800. ... 800. 800. 800.]
 [800. 800. 800. ... 800. 800. 800.]
 [800. 800. 800. ... 800. 800. 800.]]
1.2788190841674805


In [24]:
"""
Aquí defino un nuevo producto de matrices con dos ciclos for, en lugar de tres, de este
modo busco evitar tantas operaciones a diferencia de la función hecha en clase
"""

def producto_mat_por_vec(A, B):
  """
  Realiza el producto matricial de una matriz A por un vector B.

  Parámetros:
  -----------
  A : numpy.ndarray
      Una matriz de tamaño (m, n), donde m es el número de filas y n es el número de columnas.
  B : numpy.ndarray
      Un vector (o matriz de una sola columna) de tamaño (n, 1).

  Retorno:
  --------
  C : numpy.ndarray
    Una matriz de tamaño (m, 1) que contiene el resultado del producto matricial A × B.
  np.NaN : float
  Si las dimensiones de A y B no son compatibles para la multiplicación matricial.

  Observaciones:
  --------------
  1. La función verifica que el número de columnas de A coincida con el número de filas de B.
  2. La matriz resultado C se inicializa con ceros y tiene dimensiones (m, 1).
  3. La multiplicación se realiza utilizando bucles anidados y vectorización.
  4. La notación [i:j] en Python extrae elementos desde la posición i hasta la posición j-1.
  """
  # Verificar que las dimensiones de las matrices sean compatibles
  if A.shape[1] != B.shape[0]:
    return np.NaN

  # Obtener las dimensiones de las matrices
  f_A, col_A = A.shape
  f_B, col_B = B.shape

  # Inicializar la matriz resultado con ceros
  C = np.zeros((f_A, col_B))

  # Realizar el producto matricial utilizando dos bucles y vectorización
  for i in range(f_A):
    for j in range(col_B):
      C[i, j] = sum(A[i, :] * B[:, j])
    """
    De este último bloque se utiliza una propiedad de índices propia de Python,
    la notación [i:j] denota la extracción de índices desde la posición i
    hasta la posición j-1, hay que tener cuidado que es *j-1*.
    """
  return C

In [19]:

def multiply_matrices_por_bloques(A, B, tamaño):
  """
    Realiza la multiplicación de dos matrices A y B utilizando un enfoque de bloques.

    Parámetros:
    -----------
    A : numpy.ndarray
        Una matriz de tamaño (m, n), donde m es el número de filas y n es el número de columnas.
    B : numpy.ndarray
        Una matriz de tamaño (p, q), donde p es el número de filas y q es el número de columnas.
    tamaño : int
        El tamaño de los bloques en los que se dividirán las matrices para la multiplicación.

    Retorno:
    --------
    C : numpy.ndarray
        Una matriz de tamaño (m, q) que contiene el resultado del producto matricial A × B.
    np.NaN : float
        Si las dimensiones de A y B no son compatibles para la multiplicación matricial.

    Observaciones:
    --------------
    1. La función verifica que el número de columnas de A coincida con el número de filas de B.
    2. La matriz resultado C se inicializa con ceros y tiene dimensiones (m, q).
    3. La multiplicación se realiza dividiendo las matrices en bloques más pequeños.
    4. La notación [i:j] en Python extrae elementos desde la posición i hasta la posición j-1.
    5. La función utiliza la función producto_mat_por_vec para multiplicar los bloques.
  """
  # Obtener las dimensiones de las matrices
  m, n = A.shape
  p, q = B.shape

  # Verificar que las dimensiones sean compatibles para la multiplicación
  if n != p:
    return np.NaN

  # Inicializar la matriz resultante C con ceros
  C = np.zeros((m, q))

  # Multiplicación por bloques
  for i in range(0, m, tamaño):
    for j in range(0, q, tamaño):
      for k in range(0, n, tamaño):
        #damos los saltos del tamañan especificado
        # Definir los límites de los bloques
        i_fin = min(i + tamaño, m)
        j_fin = min(j + tamaño, q)
        k_fin = min(k + tamaño, n)
        """
        La idea del bloque anterior es tomar bloques de tamaño, si este supera en cierto
        punto el tamaño de la matriz, por decir, que fuera de 7x7 y son bloque de 4 entonces
        tomaría en lugar de un bloque de 4x4 sería de 3x3, para eso se definen donde
        *termina* cada paso del ciclo.
        Para así tomar los últimos bloques de 3x3 y no de 4x4 y evitar errores fuera de rango
        Notese detalle importante, el k_end es el final del paso para la matriz resultante
        del producto, en ese sentido nos interesa que no rebase el número que *conecta* por
        criterio al producto de matrices, que es el num de columnas de A y renglones de B
        En el resto de casos, para i,j nos interesa llevar bien y no tener fueras de rango
        de las filas de A y de las columas de B
        """
        A_block = A[i:i_fin, k:k_fin]
        B_block = B[k:k_fin, j:j_fin]
        C_block = C[i:i_fin, j:j_fin]

        """
        De este último bloque se utiliza una propiedad de índices propia de Python,
        la notación [i:j] denota la extracción de índices desde la posición i
        hasta la posición j-1, hay que tener cuidado que es *j-1*.
        Para el caso de las matrices se especifican primero el rango de filas
        y luego el rango de las columnas
        """

        # Multiplicar los bloques y sumar al bloque de C
        C[i:i_fin, j:j_fin] = C_block + producto_mat_por_vec(A_block, B_block)

  return C

In [23]:
inicio = time.time()
multiply_matrices_por_bloques(A,B,14)
fin = time.time()
print(fin-inicio)
print(multiply_matrices_por_bloques(A,B,9))

0.3341853618621826
[[800. 800. 800. ... 800. 800. 800.]
 [800. 800. 800. ... 800. 800. 800.]
 [800. 800. 800. ... 800. 800. 800.]
 ...
 [800. 800. 800. ... 800. 800. 800.]
 [800. 800. 800. ... 800. 800. 800.]
 [800. 800. 800. ... 800. 800. 800.]]
