

---


Nombre de los integrantes


*   Cruz Pérez Joshua Santiago
*   Hernández Banda Oziel
*   Jimenez Borzani Naomi Daniela
*   Paredes Hernández Ximena


---


## Ejercicio 25.

Programar la Factorización de Cholesky dada por:

(a)

$A = LL^T$ , L triangular inferior.

(b)

 $A = L D L^T$
, L triangular inferior y D diagonal.

In [ ]:
import numpy as np

def Cholesky(A):
    """
    Realiza la descomposición de Cholesky clásica de una matriz simétrica definida positiva.

    Parámetros
    ----------
    A : numpy.ndarray
        Matriz cuadrada simétrica y definida positiva de dimensión (n, n)

    Retorna
    -------
    L : numpy.ndarray
        Matriz triangular inferior con diagonal positiva
    L.T : numpy.ndarray
        Matriz triangular superior (transpuesta de L)

    Notas
    -----
    - Implementación directa del algoritmo de Cholesky-Banachiewicz
    - Devuelve matrices tales que A = L @ L.T (factorización LLᵀ)
    - Requiere que la matriz sea:
      * Simétrica exactamente (A = A.T)
      * Definida positiva (autovalores > 0)
    - Complejidad computacional: O(n³/3)

    Ejemplos
    --------
    >>> A = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]])
    >>> L, LT = Cholesky(A)
    >>> np.allclose(A, L @ LT)
    True
    """
    n = A.shape[0]
    L = np.zeros_like(A)

    for i in range(n):
        for j in range(i+1):
            if i == j:
                sum = 0.0
                for k in range(i):
                    sum += L[i][k] * L[i][k]
                L[i][i] = np.sqrt(A[i][i] - sum)
            else:
                sum = 0.0
                for k in range(j):
                    sum += L[i][k] * L[j][k]
                L[i][j] = (A[i][j] - sum) / L[j][j]
    return L, L.T


def Cholesky2(A):
    """
    Versión alternativa de la descomposición de Cholesky usando eliminación Gaussiana.

    Parámetros
    ----------
    A : numpy.ndarray
        Matriz cuadrada simétrica y definida positiva de dimensión (n, n)

    Retorna
    -------
    L : numpy.ndarray
        Matriz triangular inferior con diagonal unitaria
    U : numpy.ndarray
        Matriz triangular superior
    D : numpy.ndarray
        Matriz diagonal (transpuesta de L en este caso)

    Notas
    -----
    - Implementación basada en la factorización LDLᵀ
    - Devuelve matrices tales que A = L @ U @ L.T (donde U es diagonal)
    - Más estable numéricamente para matrices casi singulares
    - Requiere simetría pero no almacenamiento explícito de ambas mitades

    Ejemplos
    --------
    >>> A = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]])
    >>> L, U, D = Cholesky2(A)
    >>> np.allclose(A, L @ U @ D)
    True
    """
    n = A.shape[0]
    L = np.zeros_like(A)
    U = np.copy(A)
    L = np.eye(A.shape[0])
    aux = []

    for i in range(n):
        Li = np.eye(n)
        for j in range(i+1, n):
            Li[j,i] = -U[j,i]/U[i,i]
            L[j,i] = U[j,i]/U[i,i]
        U = Li @ U
        aux.append(np.copy(Li.T))

    for i in range(len(aux)):
        U = U @ aux[i]

    return L, U, L.T

In [ ]:
A = np.array([
    [1, -1, 1],
    [-1, 5, -3],
    [1, -3, 6]
])

L,L_2 = Cholesky(A)

print(L)
print(L_2)

print("Comprobación:")
print(L@L_2)

print("================")
L,D,L_2 = Cholesky2(A)

print(L)
print(D)
print(L_2)

print("Comprobación:")
print(L@D@L_2)


[[ 1  0  0]
 [-1  2  0]
 [ 1 -1  2]]
[[ 1 -1  1]
 [ 0  2 -1]
 [ 0  0  2]]
Comprobación:
[[ 1 -1  1]
 [-1  5 -3]
 [ 1 -3  6]]
[[ 1.   0.   0. ]
 [-1.   1.   0. ]
 [ 1.  -0.5  1. ]]
[[1. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]
[[ 1.  -1.   1. ]
 [ 0.   1.  -0.5]
 [ 0.   0.   1. ]]
Comprobación:
[[ 1. -1.  1.]
 [-1.  5. -3.]
 [ 1. -3.  6.]]
