

---


Nombre de los integrantes


*   Cruz Pérez Joshua Santiago
*   Hernández Banda Oziel
*   Jimenez Borzani Naomi Daniela
*   Paredes Hernández Ximena


---


# Ejercicio 21

Resolver cada sistema $A \bar{x}= - b$ con las rutinas:

• Factorización LU.

• Factorización LU con pivoteo parcial.

• Factorización LU con pivoteo total.

Comparar los resultados.

(a)
$$
A=\left[\begin{array}{ccc}
4 & -1 & 3 \\
-8 & 4 & -7 \\
12 & 1 & 8
\end{array}\right] ; \quad \bar{b}=\left[\begin{array}{c}
-8 \\
19 \\
-19
\end{array}\right]
$$
(b)
$$
A=\left[\begin{array}{cccc}
1 & 4 & -2 & 1 \\
-2 & -4 & -3 & 1 \\
1 & 16 & -17 & 9 \\
2 & 4 & -9 & -3
\end{array}\right] ; \quad \bar{b}=\left[\begin{array}{c}
3.5 \\
-2.5 \\
15 \\
10.5
\end{array}\right]
$$
(c)
$$
A=\left[\begin{array}{ccccc}
4 & 5 & -1 & 2 & 3 \\
12 & 13 & 0 & 10 & 3 \\
-8 & -8 & 5 & -11 & 4 \\
16 & 18 & -7 & 20 & 4 \\
-4 & -9 & 31 & -31 & -1
\end{array}\right] ; \quad \bar{b}=\left[\begin{array}{c}
34 \\
93 \\
-33 \\
131 \\
-58
\end{array}\right]
$$



---

Primero definimos las funciones a utilizar y las bibliotecas importadas


---



In [ ]:
import numpy as np
from numpy import linalg as LA

In [ ]:
def SustitucionDelante(Mat, b):
    """
    Realiza la sustitución hacia adelante para resolver un sistema de ecuaciones lineales
    representado por una matriz triangular inferior.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Una matriz triangular inferior de tamaño n x n.
    b : numpy.ndarray
        Un vector de términos independientes de tamaño n.

    Retorna:
    --------
    x : numpy.ndarray
        Un vector solución de tamaño n que satisface la ecuación Mat @ x = b.

    Descripción:
    ------------
    Esta función resuelve un sistema de ecuaciones lineales de la forma Mat @ x = b,
    donde Mat es una matriz triangular inferior. Utiliza el método de sustitución hacia adelante,
    comenzando desde la primera fila de la matriz y avanzando hacia la última.

    Ejemplo:
    --------
    >>> Mat = np.array([[1, 0, 0],
    ...                 [2, 3, 0],
    ...                 [4, 5, 6]])
    >>> b = np.array([1, 8, 32])
    >>> SustitucionDelante(Mat, b)
    array([1., 2., 3.])
    """
    n = Mat.shape[0]
    x = np.zeros(n)

    for i in range(n):
        SumCum = 0.0
        for j in range(i):
            SumCum += Mat[i, j] * x[j]
        x[i] = (b[i] - SumCum) / Mat[i, i]

    return x



def SustitucionAtras(Mat, b):
    """
    Realiza la sustitución hacia atrás para resolver un sistema de ecuaciones lineales
    representado por una matriz triangular superior.

    Parámetros:
    -----------
    Mat : numpy.ndarray
        Una matriz triangular superior de tamaño n x n.
    b : numpy.ndarray
        Un vector de términos independientes de tamaño n.

    Retorna:
    --------
    x : numpy.ndarray
        Un vector solución de tamaño n que satisface la ecuación Mat @ x = b.

    Descripción:
    ------------
    Esta función resuelve un sistema de ecuaciones lineales de la forma Mat @ x = b,
    donde Mat es una matriz triangular superior. Utiliza el método de sustitución hacia atrás,
    comenzando desde la última fila de la matriz y avanzando hacia la primera.

    Ejemplo:
    --------
    >>> Mat = np.array([[3, 2, 1],
    ...                 [0, 2, 1],
    ...                 [0, 0, 1]])
    >>> b = np.array([6, 4, 1])
    >>> SustitucionAtras(Mat, b)
    array([1., 1., 1.])
    """
    n = Mat.shape[0]
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        SumCum = 0.0
        for j in range(i+1, n):
            SumCum += Mat[i, j] * x[j]
        x[i] = (b[i] - SumCum) / Mat[i, i]

    return x



import numpy as np

def LU(A):
    """
    Realiza la descomposición LU de una matriz cuadrada usando el método de Doolittle.

    Parámetros
    ----------
    A : numpy.ndarray
        Matriz cuadrada de forma (n, n) a descomponer

    Retorna
    -------
    L : numpy.ndarray
        Matriz triangular inferior con unos en la diagonal
    U : numpy.ndarray
        Matriz triangular superior

    Notas
    -----
    - Implementa el algoritmo de Doolittle donde L tiene 1's en la diagonal
    - Retorna matrices tales que A = L @ U
    - Fallará si algún elemento diagonal de U es cero (no implementa pivoteo)
    - Complejidad computacional: O(n³)

    Ejemplos
    --------
    >>> A = np.array([[4, 3], [6, 3]])
    >>> L, U = LU(A)
    >>> L
    array([[1. , 0. ],
           [1.5, 1. ]])
    """
    U = np.copy(A)
    L = np.eye(A.shape[0])

    for i in range(A.shape[0]):
        Li = np.eye(A.shape[0])
        for j in range(i+1, A.shape[0]):
            Li[j,i] = -U[j,i]/U[i,i]
            L[j,i] = U[j,i]/U[i,i]
        U = Li @ U
    return L, U

def SolverLU(A, b):
    """
    Resuelve un sistema lineal Ax = b usando descomposición LU.

    Parámetros
    ----------
    A : numpy.ndarray
        Matriz de coeficientes cuadrada de forma (n, n)
    b : numpy.ndarray
        Vector de términos independientes de forma (n,)

    Retorna
    -------
    x : numpy.ndarray
        Vector solución de forma (n,)

    Notas
    -----
    - Requiere las funciones auxiliares SustitucionDelante() (sustitución hacia adelante)
      y SustitucionAtras() (sustitución hacia atrás)
    - Implementa el proceso en dos etapas:
      1. Descompone A en LU
      2. Resuelve Ly = b y luego Ux = y
    - No implementa pivoteo parcial
    - Versión inestable para matrices mal condicionadas

    Ejemplos
    --------
    >>> A = np.array([[2, -1], [1, 3]])
    >>> b = np.array([1, 2])
    >>> SolverLU(A, b)
    array([ 0.71428571,  0.42857143])
    """
    L, U = LU(A)
    y = SustitucionDelante(L, b)  # Resuelve Ly = b
    x = SustitucionAtras(U, y)    # Resuelve Ux = y
    return x

def Permutaciones(A, b):
    """
    Realiza pivoteo parcial con permutación de filas para la matriz A y vector b.

    Parámetros
    ----------
    A : numpy.ndarray
        Matriz cuadrada de coeficientes de forma (n, n)
    b : numpy.ndarray
        Vector de términos independientes de forma (n,)

    Retorna
    -------
    P : numpy.ndarray
        Matriz de permutación de forma (n, n)
    U : numpy.ndarray
        Versión permutada de la matriz A
    x : numpy.ndarray
        Versión permutada del vector b

    Notas
    -----
    - Implementa pivoteo parcial seleccionando el elemento máximo en la columna actual
    - Modifica tanto la matriz como el vector para mantener la consistencia del sistema
    - La matriz de permutación P satisface P @ A = U y P @ b = x
    - Requiere que A sea no singular para resultados correctos

    Ejemplos
    --------
    >>> A = np.array([[0, 2], [1, 3]])
    >>> b = np.array([1, 4])
    >>> P, U, x = Permutaciones(A, b)
    >>> U
    array([[1, 3],
           [0, 2]])
    """
    U = np.copy(A)
    x = np.copy(b)
    P = np.eye(A.shape[0])

    for j in range(A.shape[0]):
        k = np.argmax(np.abs(A[j:, j])) + j
        U[[j, k]] = U[[k, j]]  # Intercambia filas en la matriz
        P[[j, k]] = P[[k, j]]  # Actualiza matriz de permutación
        x[[j, k]] = x[[k, j]]  # Intercambia elementos correspondientes en b

    return P, U, x

def Solver_LU_Pivot_Partial(A, b):
    """
    Resuelve un sistema lineal Ax = b usando descomposición LU con pivoteo parcial.

    Parámetros
    ----------
    A : numpy.ndarray
        Matriz cuadrada de coeficientes de forma (n, n)
    b : numpy.ndarray
        Vector de términos independientes de forma (n,)

    Retorna
    -------
    x : numpy.ndarray
        Vector solución de forma (n,)

    Notas
    -----
    - Utiliza Permutaciones() para el pivoteo parcial
    - Usa SolverLU() para la solución después de la permutación
    - Más estable numéricamente que la descomposición LU estándar
    - La matriz A debe ser no singular

    Ver también
    --------
    Permutaciones : Función de pivoteo parcial utilizada
    SolverLU : Resolución LU llamada después de la permutación

    Ejemplos
    --------
    >>> A = np.array([[0, 1], [2, 3]])
    >>> b = np.array([4, 5])
    >>> Solver_LU_Pivot_Partial(A, b)
    array([-3.5,  4. ])
    """
    P, Ap, bp = Permutaciones(A, b)
    x = SolverLU(Ap, bp)
    return x

def Permutaciones_t(A, b):
    n = A.shape[0]  # Tamaño de la matriz (n x n)
    U = np.copy(A)  # Copia de la matriz A para no modificarla directamente
    x = np.copy(b)  # Copia del vector b
    P = np.eye(n)   # Matriz de permutación de filas (inicialmente identidad)
    Q = np.eye(n)   # Matriz de permutación de columnas (inicialmente identidad)

    for k in range(n - 1):
        # --- PASO 1: Encontrar el pivote máximo en la submatriz U[k:, k:] ---
        # np.abs(U[k:, k:]): Valores absolutos de la submatriz desde (k,k) hasta el final
        # np.argmax(...): Índice lineal del elemento con mayor valor absoluto (en arreglo aplanado)
        # np.unravel_index(...): Convierte el índice lineal a coordenadas (fila, columna) en la submatriz
        max_row, max_col = np.unravel_index(np.argmax(np.abs(U[k:, k:])), (n - k, n - k))

        # Ajustar índices para referenciar la posición en la matriz original U (no solo la submatriz)
        max_row += k
        max_col += k

        # --- PASO 2: Intercambiar filas para llevar el pivote a la posición (k,k) ---
        # Intercambia filas en U
        U[[k, max_row]] = U[[max_row, k]]
        # Intercambia filas en la matriz de permutación P
        P[[k, max_row]] = P[[max_row, k]]
        # Intercambia elementos en el vector x
        x[[k, max_row]] = x[[max_row, k]]

        # --- PASO 3: Intercambiar columnas para optimizar la factorización ---
        # Intercambia columnas en U
        U[:, [k, max_col]] = U[:, [max_col, k]]
        # Intercambia columnas en la matriz de permutación Q
        Q[:, [k, max_col]] = Q[:, [max_col, k]]

    return P, Q, U, x  # Devuelve: Matrices de permutación, matriz triangular, y vector modificado

def Solver_LU_Pivot_Total(A, b):
    """
    Resuelve un sistema lineal Ax = b usando descomposición LU con pivoteo total.

    Esta función implementa el método de eliminación gaussiana con pivoteo completo,
    que incluye permutaciones tanto de filas como de columnas para mayor estabilidad numérica.

    Parámetros
    ----------
    A : numpy.ndarray
        Matriz cuadrada de coeficientes de dimensión (n, n).
        Debe ser una matriz no singular.
    b : numpy.ndarray
        Vector de términos independientes de dimensión (n,).

    Retorna
    -------
    x : numpy.ndarray
        Vector solución de dimensión (n,) que satisface Ax = b.

    Notas
    -----
    - Utiliza pivoteo total (intercambio de filas y columnas) para mejorar la estabilidad numérica.
    - Requiere las funciones auxiliares:
      * Permutaciones(): Realiza el pivoteo total y devuelve las matrices de permutación
      * SolverLU(): Resuelve el sistema una vez permutado
    - El pivoteo total es más estable que el pivoteo parcial, especialmente para matrices mal condicionadas.
    - La solución obtenida está en el orden original de las variables (se aplica Q para reordenar).

    Proceso
    -------
    1. Realiza pivoteo total obteniendo: P*A*Q = A_g
    2. Permuta el vector b: b_g = P*b
    3. Resuelve el sistema permutado A_g x_g = b_g
    4. Reordena la solución: x = Q*x_g

    Ejemplos
    --------
    >>> import numpy as np
    >>> A = np.array([[0, 2], [1, 1]])
    >>> b = np.array([1, 0])
    >>> x = Solver_LU_Pivot_Total(A, b)
    >>> print("Solución:", x)
    Solución: [-1.   0.5]
    """
    P, Q, A_g, b_g = Permutaciones_t(A, b)
    x = SolverLU(A_g, b_g)
    x = Q @ x

    return x




---

Prodecemos a resolver los siguientes sistemas

---



In [ ]:
# Sistema (a)
A_a = np.array([
    [4, -1, 3],
    [-8, 4, -7],
    [12, 1, 8]
])
b_a = np.array([-8, 19, -19])

# Sistema (b)
A_b = np.array([
    [1, 4, -2, 1],
    [-2, -4, -3, 1],
    [1, 16, -17, 9],
    [2, 4, -9, -3]
])
b_b = np.array([3.5, -2.5, 15, 10.5])

# Sistema (c)
A_c = np.array([
    [4, 5, -1, 2, 3],
    [12, 13, 0, 10, 3],
    [-8, -8, 5, -11, 4],
    [16, 18, -7, 20, 4],
    [-4, -9, 31, -31, -1]
])
b_c = np.array([34, 93, -33, 131, -58])


In [ ]:
## Sistema (a)
Sol_1 = SolverLU(A_a, b_a)
print("Solución del sistema (a):")
print(Sol_1)

Sol_2 = Solver_LU_Pivot_Partial(A_a, b_a)
print("Solución del sistema (a) con pivoteo parcial:")
print(Sol_2)

Sol_3 = Solver_LU_Pivot_Total(A_a, b_a)
print("Solución del sistema (a) con pivoteo total:")
print(Sol_3)

print ("====================")

## Sistema (b)

Sol_1 = SolverLU(A_b, b_b)
print("Solución del sistema (b):")
print(Sol_1)

Sol_2 = Solver_LU_Pivot_Partial(A_b, b_b)
print("Solución del sistema (b) con pivoteo parcial:")
print(Sol_2)

Sol_3 = Solver_LU_Pivot_Total(A_b, b_b)
print("Solución del sistema (b) con pivoteo total:")
print(Sol_3)

print ("====================")

## Sistema (c)

Sol_1 = SolverLU(A_c, b_c)
print("Solución del sistema (c):")
print(Sol_1)

Sol_2 = Solver_LU_Pivot_Partial(A_c, b_c)
print("Solución del sistema (c) con pivoteo parcial:")
print(Sol_2)

Sol_3 = Solver_LU_Pivot_Total(A_c, b_c)
print("Solución del sistema (c) con pivoteo total:")
print(Sol_3)


Solución del sistema (a):
[-1.  1. -1.]
Solución del sistema (a) con pivoteo parcial:
[-1.  1. -1.]
Solución del sistema (a) con pivoteo total:
[-1.  1. -1.]
Solución del sistema (b):
[-0.5  1.  -0.5 -1. ]
Solución del sistema (b) con pivoteo parcial:
[-0.5  1.  -0.5 -1. ]
Solución del sistema (b) con pivoteo total:
[-0.5  1.  -0.5 -1. ]
Solución del sistema (c):
[1. 2. 3. 4. 5.]
Solución del sistema (c) con pivoteo parcial:
[1. 2. 3. 4. 5.]
Solución del sistema (c) con pivoteo total:
[1. 2. 3. 4. 5.]
