

---


Nombre de los integrantes


*   Cruz Pérez Joshua Santiago
*   Hernández Banda Oziel
*   Jimenez Borzani Naomi Daniela
*   Paredes Hernández Ximena


---


22. Dada la matriz
$$
A=\left(\begin{array}{ccccc}
1 & 0 & 0 & 0 & 1 \\
-1 & 1 & 0 & 0 & 1 \\
-1 & -1 & 1 & 0 & 1 \\
-1 & -1 & -1 & 1 & 1 \\
-1 & -1 & -1 & -1 & 1
\end{array}\right)
$$
(a) ¿Qué sucede cuando se usa Eliminación Gaussina con pivoteo parcial?.

In [ ]:
import numpy as np

# -------------------------
# Función de sustitución hacia adelante
# Resuelve Ly = b cuando L es una matriz triangular inferior
def SustitucionDelante(Mat, b):
    n = Mat.shape[0]
    x = np.zeros(n)  # Vector solución inicializado en ceros
    for i in range(n):
        SumCum = 0.0  # Acumulador para la suma de términos conocidos
        for j in range(i):
            SumCum += Mat[i, j] * x[j]
        x[i] = (b[i] - SumCum) / Mat[i, i]  # Se despeja x[i]
    return x

# -------------------------
# Función de sustitución hacia atrás
# Resuelve Ux = y cuando U es una matriz triangular superior
def SustitucionAtras(Mat, b):
    n = Mat.shape[0]
    x = np.zeros(n)  # Vector solución inicializado en ceros
    for i in range(n-1, -1, -1):  # Se recorre de abajo hacia arriba
        SumCum = 0.0  # Acumulador para la suma de términos conocidos
        for j in range(i+1, n):
            SumCum += Mat[i, j] * x[j]
        x[i] = (b[i] - SumCum) / Mat[i, i]  # Se despeja x[i]
    return x

# -------------------------
# Descomposición LU sin pivoteo
# Se obtiene L (matriz triangular inferior) y U (matriz triangular superior) tal que A = LU
def LU(A):
    U = np.copy(A)  # Copia de A que se transformará en U
    L = np.eye(A.shape[0])  # Matriz identidad del mismo tamaño que A (será L)

    for i in range(A.shape[0]):
        Li = np.eye(A.shape[0])  # Matriz identidad temporal para eliminar debajo del pivote
        for j in range(i+1, A.shape[0]):
            # Se calculan los coeficientes para anular los elementos debajo del pivote
            Li[j, i] = -U[j, i] / U[i, i]
            L[j, i] = U[j, i] / U[i, i]
        U = Li @ U  # Se actualiza U mediante la eliminación gaussiana
    return L, U

# -------------------------
# Resolución del sistema Ax = b usando LU sin pivoteo
def SolverLU(A, b):
    L, U = LU(A)              # Descomposición LU
    y = SustitucionDelante(L, b)  # Resolver Ly = b
    x = SustitucionAtras(U, y)    # Resolver Ux = y
    return x

# -------------------------
# Pivoteo parcial para evitar divisiones por ceros y mejorar estabilidad numérica
def Permutaciones(A, b):
    U = np.copy(A)
    x = np.copy(b)
    P = np.eye(A.shape[0])  # Matriz de permutación inicial

    for j in range(A.shape[0]):
        # Buscar el valor absoluto máximo en la columna j, desde la fila j hacia abajo
        k = np.argmax(np.abs(U[j:, j])) + j
        # Intercambiar filas en U, P y b
        U[[j, k]] = U[[k, j]]
        P[[j, k]] = P[[k, j]]
        x[[j, k]] = x[[k, j]]
    return P, U, x

# -------------------------
# Resolver el sistema Ax = b usando LU con pivoteo parcial
def Solver_LU_Pivot_Partial(A, b):
    P, Ap, bp = Permutaciones(A, b)  # Aplicar pivoteo parcial
    x = SolverLU(Ap, bp)             # Resolver el sistema con la matriz permutada
    print("Matriz de permutación P:\n", P)
    print("\nMatriz L y U ")
    L, U = LU(Ap)
    print("\nL:\n", L)
    print("\nU:\n", U)
    return x

# -------------------------
# Definición del sistema a resolver
A = np.array([
    [1,  0,  0,  0,  1],
    [-1, 1,  0,  0,  1],
    [-1, -1, 1,  0,  1],
    [-1, -1, -1, 1,  1],
    [-1, -1, -1, -1, 1]
], dtype=float)

b = np.ones(5)

# Resolución del sistema con pivoteo parcial
x = Solver_LU_Pivot_Partial(A, b)

# Mostrar la solución del sistema
print("\nSolución es :\n", x)


(b) Usar Eliminación Gaussina con pivoteo parcial para resolver sistemas de varios tamaños
(al menos 5) con vectores b elegidos por cualquier criterio. Describir como se comporta la condición de la matriz.

In [ ]:
import numpy as np

# ----------------------------------------------------
# Función de sustitución hacia adelante
# Resuelve Ly = b cuando L es una matriz triangular inferior
def SustitucionDelante(Mat, b):
    n = Mat.shape[0]
    x = np.zeros(n)  # Vector solución
    for i in range(n):
        SumCum = 0.0
        for j in range(i):
            SumCum += Mat[i, j] * x[j]
        x[i] = (b[i] - SumCum) / Mat[i, i]
    return x

# ----------------------------------------------------
# Función de sustitución hacia atrás
# Resuelve Ux = y cuando U es una matriz triangular superior
def SustitucionAtras(Mat, b):
    n = Mat.shape[0]
    x = np.zeros(n)  # Vector solución
    for i in range(n-1, -1, -1):
        SumCum = 0.0
        for j in range(i+1, n):
            SumCum += Mat[i, j] * x[j]
        x[i] = (b[i] - SumCum) / Mat[i, i]
    return x

# ----------------------------------------------------
# Descomposición LU sin pivoteo parcial
# Retorna matrices L (inferior) y U (superior) tal que A = LU
def LU(A):
    n = A.shape[0]
    U = np.copy(A)
    L = np.eye(n)  # Matriz identidad como base para L

    for i in range(n):
        for j in range(i+1, n):
            L[j, i] = U[j, i] / U[i, i]  # Factor multiplicador
            U[j, :] = U[j, :] - L[j, i] * U[i, :]  # Eliminación gaussiana
    return L, U

# ----------------------------------------------------
# Pivoteo parcial por filas
# Reordena filas de A y b para evitar divisiones por cero o valores pequeños
def Permutaciones(A, b):
    U = np.copy(A)
    x = np.copy(b)
    P = np.eye(A.shape[0])  # Matriz de permutación

    for j in range(A.shape[0]):
        # Encuentra el índice del máximo valor absoluto en la columna j desde fila j hacia abajo
        k = np.argmax(np.abs(U[j:, j])) + j
        if k != j:
            # Intercambio de filas en U, P y b
            U[[j, k]] = U[[k, j]]
            P[[j, k]] = P[[k, j]]
            x[[j, k]] = x[[k, j]]
    return P, U, x

# ----------------------------------------------------
# Solver completo que utiliza LU con pivoteo parcial
# Retorna un diccionario con todas las matrices y la solución
def Solver_LU_Pivot_Partial(A, b):
    P, Ap, bp = Permutaciones(A, b)  # Ap = P @ A, bp = P @ b
    L, U = LU(Ap)
    y = SustitucionDelante(L, bp)
    x = SustitucionAtras(U, y)

    return {
        'P': P,
        'L': L,
        'U': U,
        'A_permutada': Ap,
        'b_permutado': bp,
        'x': x
    }

# ----------------------------------------------------
# Prueba con matrices aleatorias de distintos tamaños
# Calcula condición de la matriz y error numérico ||Ax - b||
def prueb_cond():
    tamaños = [5, 10, 15, 20, 25]  # Dimensiones a evaluar

    for n in tamaños:
        print(f"\n== Sistema {n}x{n} ==")

        # Se genera una matriz aleatoria de rango completo
        while True:
            A = np.random.randn(n, n)  # Matriz A con entradas normales estándar
            if np.linalg.matrix_rank(A) == n:  # Asegurar que A es invertible
                break

        b = np.random.randn(n)  # Vector b aleatorio

        try:
            condicion = np.linalg.cond(A)  # Número de condición de A
            resultado = Solver_LU_Pivot_Partial(A, b)

            x = resultado['x']
            L = resultado['L']
            U = resultado['U']
            Ap = resultado['A_permutada']
            bp = resultado['b_permutado']

            error = np.linalg.norm(A @ x - b)  # Error absoluto ||Ax - b||

            # Impresión de resultados
            print(f"\nMatriz A:\n{A}")
            print(f"\nVector b:\n{b}")
            print(f"\nMatriz A permutada (con pivoteo parcial):\n{Ap}")
            print(f"\nVector b permutado:\n{bp}")
            print(f"\nMatriz L:\n{L}")
            print(f"\nMatriz U:\n{U}")
            print(f"\nSolución x:\n{x}")
            print(f"\nCondición de A: {condicion:.2e}")
            print(f"Error ||Ax - b||: {error:.2e}")
        except Exception as e:
            print(" Error al resolver el sistema:", e)

# ----------------------------------------------------
# Ejecutar pruebas
prueb_cond()



== Sistema 5x5 ==

Matriz A:
[[ 0.64695445 -0.2814968   1.00769562  1.85749028  2.2249614 ]
 [ 0.72347492 -0.6149272  -2.22894072 -0.611215    0.58544496]
 [-0.03717334  0.44365919 -1.06563843  0.1183306  -0.6683037 ]
 [ 0.27987984 -0.43595836 -1.66444829 -1.83446886  0.0738751 ]
 [ 1.08567686 -0.7111806   1.11701308 -1.58150065  1.36929556]]

Vector b:
[ 0.47262346 -1.16256561  0.28484805 -1.16040557  0.30137303]

Matriz A permutada (con pivoteo parcial):
[[ 1.08567686 -0.7111806   1.11701308 -1.58150065  1.36929556]
 [ 0.72347492 -0.6149272  -2.22894072 -0.611215    0.58544496]
 [ 0.27987984 -0.43595836 -1.66444829 -1.83446886  0.0738751 ]
 [ 0.64695445 -0.2814968   1.00769562  1.85749028  2.2249614 ]
 [-0.03717334  0.44365919 -1.06563843  0.1183306  -0.6683037 ]]

Vector b permutado:
[ 0.30137303 -1.16256561 -1.16040557  0.47262346  0.28484805]

Matriz L:
[[ 1.          0.          0.          0.          0.        ]
 [ 0.66638145  1.          0.          0.          0.        ]
 [

(c) Escribir una rutina que factorice la matriz (LU) con pivoteo total.

In [ ]:
import numpy as np
from numpy import linalg as LA

# --------------------------------------------------------
# Sustitución hacia adelante: resuelve Ly = b
def SustitucionDelante(Mat, b):
    n = len(b)
    x = np.zeros(n)
    for i in range(n):
        suma = 0
        for j in range(i):
            suma += Mat[i][j] * x[j]
        x[i] = (b[i] - suma) / Mat[i][i]
    return x

# --------------------------------------------------------
# Sustitución hacia atrás: resuelve Ux = y
def SustitucionAtras(Mat, b):
    n = len(b)
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        suma = 0
        for j in range(i+1, n):
            suma += Mat[i][j] * x[j]
        x[i] = (b[i] - suma) / Mat[i][i]
    return x

# --------------------------------------------------------
# Descomposición LU con pivoteo completo (filas y columnas)
# Encuentra matrices P, L, U y Q tal que PAQ = LU
def PAQ_LU(A):
    A = A.copy()
    n = A.shape[0]
    U = np.copy(A)
    P = np.eye(n)  # Matriz de permutación de filas
    Q = np.eye(n)  # Matriz de permutación de columnas
    L = np.eye(n)  # Matriz triangular inferior

    for k in range(n - 1):
        # Encontrar el pivote máximo en valor absoluto en la submatriz U[k:, k:]
        max_row, max_col = np.unravel_index(
            np.argmax(np.abs(U[k:, k:])), (n - k, n - k)
        )
        max_row += k
        max_col += k

        # Intercambiar filas en U y P (y en L si corresponde)
        if max_row != k:
            U[[k, max_row], :] = U[[max_row, k], :]
            P[[k, max_row], :] = P[[max_row, k], :]
            if k > 0:
                # También se permutan las filas de L que ya estaban llenas
                L[[k, max_row], :k] = L[[max_row, k], :k]

        # Intercambiar columnas en U y Q
        if max_col != k:
            U[:, [k, max_col]] = U[:, [max_col, k]]
            Q[:, [k, max_col]] = Q[:, [max_col, k]]

        # Eliminación gaussiana para anular los elementos debajo del pivote
        for i in range(k + 1, n):
            L[i, k] = U[i, k] / U[k, k]
            U[i, k:] = U[i, k:] - L[i, k] * U[k, k:]

    return P, L, U, Q

# --------------------------------------------------------
# Resuelve Ax = b usando PAQ = LU
def Resolver_PAQ_LU(A, b):
    P, L, U, Q = PAQ_LU(A)
    b_hat = P @ b           # Aplicar permutación de filas a b
    y = SustitucionDelante(L, b_hat)  # Resolver Ly = Pb
    z = SustitucionAtras(U, y)        # Resolver Uz = y
    x = Q @ z              # Aplicar permutación de columnas a la solución
    return P, L, U, Q, x

# --------------------------------------------------------
# Función de prueba con un sistema definido
def matrizejer():
    A = np.array([
        [1,  0,  0,  0,  1],
        [-1, 1,  0,  0,  1],
        [-1, -1, 1,  0,  1],
        [-1, -1, -1, 1,  1],
        [-1, -1, -1, -1, 1]
    ], dtype=float)

    b = np.ones(5)

    # Resolver el sistema con pivoteo completo
    P, L, U, Q, x = Resolver_PAQ_LU(A, b)

    # Mostrar resultados
    print("\nMatriz original A:\n", A)
    print("\nVector b:\n", b)
    print("\nMatriz de permutación de filas P:\n", P)
    print("\nMatriz de permutación de columnas Q:\n", Q)
    print("\nMatriz L:\n", L)
    print("\nMatriz U:\n", U)
    print("\nSolución x:\n", x)

# Ejecutar la prueba
matrizejer()



Matriz original A:
 [[ 1.  0.  0.  0.  1.]
 [-1.  1.  0.  0.  1.]
 [-1. -1.  1.  0.  1.]
 [-1. -1. -1.  1.  1.]
 [-1. -1. -1. -1.  1.]]

Vector b:
 [1. 1. 1. 1. 1.]

Matriz de permutación de filas P:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Matriz de permutación de columnas Q:
 [[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]

Matriz L:
 [[ 1.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [-1.  1.  1.  0.  0.]
 [-1.  1.  1.  1.  0.]
 [-1.  1.  1.  1.  1.]]

Matriz U:
 [[ 1.  1.  0.  0.  0.]
 [ 0.  2.  1.  0.  0.]
 [ 0.  0. -2.  1.  0.]
 [ 0.  0.  0. -2.  1.]
 [ 0.  0.  0.  0. -2.]]

Solución x:
 [0. 0. 0. 0. 1.]
