

---


Nombre de los integrantes


*   Cruz Pérez Joshua Santiago
*   Hernández Banda Oziel
*   Jimenez Borzani Naomi Daniela
*   Paredes Hernández Ximena


---


In [ ]:
import numpy as np
from numpy import linalg as LA

In [ ]:
A=np.array([[2,4,-2],[4,9,-3],[-2,-1,7]])
b=np.array([2, 8, 10])

In [ ]:
def SustitucionDelante(Mat, b):
    """
    Realiza sustitución hacia adelante para resolver sistemas triangulares inferiores.

    Parámetros:
    Mat -- Matriz triangular inferior (n x n)
    b   -- Vector de términos independientes (n)

    Retorna:
    x   -- Vector solución del sistema Mat @ x = b
    """

    n = Mat.shape[0]
    x = np.zeros(n)

    for i in range(n):
        SumCum = 0.0
        for j in range(i):
            SumCum += Mat[i, j] * x[j]
        x[i] = (b[i] - SumCum) / Mat[i, i]

    return x

def SustitucionAtras(Mat, b):
    """
    Realiza sustitución hacia atrás para resolver sistemas triangulares superiores.

    Parámetros:
    Mat -- Matriz triangular superior (n x n)
    b   -- Vector de términos independientes (n)

    Retorna:
    x   -- Vector solución del sistema Mat @ x = b
    """

    n = Mat.shape[0]
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        SumCum = 0.0
        for j in range(i+1, n):
            SumCum += Mat[i, j] * x[j]
        x[i] = (b[i] - SumCum) / Mat[i, i]

    return x

# Eliminación Gaussiana = Descomposición LU

def LU(A):
    """
    Realiza la descomposición LU de una matriz usando eliminación Gaussiana.

    La descomposición LU factoriza una matriz A en el producto de:
    A = L @ U, donde:
    - L es una matriz triangular inferior con 1's en la diagonal
    - U es una matriz triangular superior

    Parámetros:
    A -- Matriz cuadrada a descomponer (n x n)

    Retorna:
    L -- Matriz triangular inferior con diagonal unitaria
    U -- Matriz triangular superior

    NOTA:
    - Implementa el método de eliminación Gaussiana sin pivoteo
    - Utiliza las funciones SustitucionDelante y SustitucionAtras
    """
    U = np.copy(A)
    L = np.eye(A.shape[0])

    for i in range(A.shape[0]):
        Li = np.eye(A.shape[0])
        for j in range(i+1, A.shape[0]):
            # Calculamos el factor de multiplicación
            Li[j, i] = -U[j, i] / U[i, i]
            # Actualizamos la matriz U
            L[j, i] = U[j, i] / U[i, i]
        U = Li @ U

    return L, U


In [ ]:
def SolverLU(A, b):
    """
    Resuelve un sistema lineal Ax = b utilizando la descomposición LU.

    El método realiza los siguientes pasos:
    1. Descompone la matriz A en matrices triangulares L (inferior) y U (superior)
    2. Resuelve el sistema triangular inferior Ly = b usando sustitución hacia adelante
    3. Resuelve el sistema triangular superior Ux = y usando sustitución hacia atrás

    Parámetros:
    A -- Matriz cuadrada de coeficientes (n x n)
    b -- Vector de términos independientes (n)

    Retorna:
    x -- Vector solución del sistema Ax = b

    Ejemplo:
    >>> A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
    >>> b = np.array([1, 0, 1])
    >>> SolverLU(A, b)
    array([1., 1., 1.])

    NOTA:
    - Utiliza la implementación propia de LU sin pivoteo
    - Incluye verificación contra la solución de numpy para validar resultados
    """
    L, U = LU(A)
    y = SustitucionDelante(L, b)
    x = SustitucionAtras(U, y)
    return x

#----------------- RESOLVIENDO PARA A y b PLANTEADOS EN LA PRÁCTICA -----------------#
"""
Sección de resolución del sistema lineal y verificación de resultados

Proceso:
1. Se llama a SolverLU con la matriz A y vector b definidos previamente
2. Se imprime la solución obtenida por el método LU
3. Se verifica la solución comparando con la implementación de numpy.linalg.solve

Propósito:
- Demostrar el funcionamiento del solver LU implementado
- Validar los resultados contra una implementación de referencia
- Mostrar el formato de salida de la solución

Notas:
- La matriz A y vector b están definidos en la parte superior del código
- La verificación con numpy sirve como prueba de los resultados del algoritmo
"""

x = SolverLU(A, b)
print("La solución del sistema Ax = b es:")
print(x)

# Verificación con numpy
print("\nLa solución del sistema con numpy es:")
print(np.linalg.solve(A, b))

La solución del sistema Ax = b es:
[-7.  4.  0.]

La solución del sistema con numpy es:
[-7.  4.  0.]
